# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8081acbab05c4c417cd3b5f1fbe9228c5d110194cfcfd7dfb354f25486b3e658dab057960848038371139946e70cb770667f6514a6bf592330456686a1839fe6

test:
  secret_key_base: b5fb4cf25d2c8773ead5d2a0296eb08f480a318f625ea768c0ced70dbc70fbac38ca76709f576add79418f79a13d5ff6d7a65834aacaf739f91cb005990fd9d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
